yatube/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
"""Файл с перехватами url- ов."""
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('', views.index, name='index'),
        path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/', 
         views.profile_follow,
         name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),

]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/', LogoutView.as_view(template_name='users/logout.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view
        (template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view
        (template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view
        (template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view
        (template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view
        (template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view
        (template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    )
]

yatube/yatube/urls.py
"""Файл для перехватов url-ов."""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'yatube'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'

yatube/posts/models.py
"""Создание моделей Group и Posts для админ-зоны сайта."""
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Модель для работы с группами в базе данных."""
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Код группы в url', unique=True)
    description = models.TextField('Описание', max_length=500)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        """Метод, который возвращает строковое представление объекта."""
        return self.title


class Post(models.Model):
    """Модель для работы с постами в базе данных."""
    text = models.TextField(
        'Текст',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='ID автора сообщения'
    )

    group = models.ForeignKey(
        Group, blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
    )

    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )

    class Meta:
        verbose_name = 'Сообщение',
        verbose_name_plural = 'Сообщения',
        ordering = ('-pub_date'),

    def __str__(self):
        """Метод, который возвращает строковое представление объекта."""
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Я пока не понял',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="following")

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:

        model = Post
        help_text = 'Текст сообщения и группа'
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        help_text = 'Текст сообщения и группа'
        fields = ('text', )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


# Описать класс AboutAuthorView для страницы about/author
class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'СТРаница'
        context['text'] = ('Всё равно страшно')
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Очень страница'
        context['text'] = ('У меня Ай Ай')
        return context

yatube/core/views.py
from django.shortcuts import render

def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)

def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
"""Файл для отправки и отображения информации из баз в шаблоны."""
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import PostForm, CommentForm
from django.urls import reverse
from django.views.decorators.cache import cache_page

from .models import Follow, Group, Post, User, Comment

from yatube.settings import COUNT_POST_FOR_PAGE

@cache_page(60 * 15, key_prefix='index_page')
def index(request):
    """Метод для отображения информации  на главной странице."""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, COUNT_POST_FOR_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': post_list,
        'year': datetime.now().year,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Метод для отображения всех других страниц кроме главной."""
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.all()
    paginator = Paginator(post_list, COUNT_POST_FOR_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'post_list': post_list,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = (
        Post.objects.filter(author__username=username)
    )
    paginator = Paginator(posts, COUNT_POST_FOR_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'page_obj': page_obj,
        'author': user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_count = Post.objects.select_related('author').filter(
        author=post.author).count()
    context = {
        'post': post,
        'post_count': post_count,
    }
    return render(request, 'posts/post_detail.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = Comment.objects.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.user.is_authenticated:

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', request.user)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post_list = Post.objects.all()
    post = get_object_or_404(Post, id=post_id, author=request.user)
    form = PostForm(
        request.POST,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'GET':
        return render(request, 'posts/create_post.html',
                      {'post_list': post_list,
                       'post': post,
                       'is_edit': True,
                       'form': form,
                       'post_id': post_id,
                       })
    form = PostForm(
        request.POST,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST':
        form = PostForm(
            request.POST,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            form.save()
        return redirect('posts:post_detail', post_id=post.pk)
    context = {'post_id': post_id,
               'form': form,
               'post': post,
               'is_edit': True
               }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    list_of_posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(list_of_posts, COUNT_POST_FOR_PAGE)
    page_namber = request.GET.get('page')
    page_obj = paginator.get_page(page_namber)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user=request.user
    author=User.objects.get(username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username)
# def profile_follow(request, username):
#     user = request.user
#     author = User.objects.get(username=username)
#     is_follower = Follow.objects.filter(user=user, author=author)
#     if user != author and not is_follower.exists():
#         Follow.objects.filter(user=request.user, author=author)
#     return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/posts/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  Новый пост
{% endblock %}
{% block content %}
{% load thumbnail %}   
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать запись
              {% else %}       
                Добавить запись
              {% endif %}            
            </div>
            <div class="card-body">        
              <form method="post" enctype="multipart/form-data" 
                        action="{% if is_edit %} {% url 'posts:post_edit' post_id %}
                        {% else %} {% url 'posts:post_create' %} {% endif %}">
                          {% csrf_token %}          
                            <div class="form-group row my-3 p-3">
                              <label for="id_text">
                                Текст поста                  
                                <span class="required text-danger" >*</span>                  
                              </label>
                              <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                              {{ post.text }}</textarea>                
                              <small id="id_text-help" class="form-text text-muted">
                                {% if is_edit %}
                                  Отредактируйте текст поста
                                {% else %}       
                                  Текст нового поста
                                {% endif %}  
                              </small>                  
                            </div>            
                          <div class="form-group row my-3 p-3">
                            <label for="id_group">
                              Группа                  
                            </label>
                            <select name="group" class="form-control" id="id_group">
                              <option value="" selected>{{post.group}}</option>
                              {% for groups in post_list %}
                              <option value="1"> {{groups.group }}</option>
                              {% endfor %}
                            </select>

                            <small id="id_group-help" class="form-text text-muted">
                              Группа, к которой будет относиться пост
                            </small>
                          </div>
                          <div class="form-group row my-3 p-3">
                            <label for="id_image">
                              Картинка                      
                            </label>
                            <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                          </div>
                          <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                              {% if is_edit %}
                                Сохранить
                              {% else %}
                                Добавить
                              {% endif %}
                            </button>
                          </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Избранные авторы{% endblock %}
{% block header %}Избранные авторы{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load thumbnail %}
<div class="container py-5">  
  <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор:
        <a href= "{% url 'posts:profile' post.author.username %}">
          {% if post.author.get_full_name %}
            {{ post.author.get_full_name }}
          {% else %}
            {{ post.author.username }}
          {% endif %} 
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </li>
    </ul>
    <p>{{ post.text }}</p>

    {% thumbnail post.image "960x339" crop="center"  upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}" weidth=50% height=25%>
    {% endthumbnail %}

    {{ post.group }} 
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</article>
</div>
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock title %}
{% block content %}
{% load thumbnail %}
  <main>
    <div class="container">
    {% block header %} {{group.title}}{% endblock %}
    <p> {{group.description}} </p>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор:
            {% if post.author.get_full_name  %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.get_full_name }}
              </a>
            {% else %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.username }}
              </a>
            {% endif %}            
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} 
        {% if post.group %}   
          <a href="{% url 'posts:index' %}">Вернуться на главную</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    </div>   
  </main>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">  
  <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор:
        <a href= "{% url 'posts:profile' post.author.username %}">
          {% if post.author.get_full_name %}
            {{ post.author.get_full_name }}
          {% else %}
            {{ post.author.username }}
          {% endif %} 
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </li>
    </ul>
    <p>{{ post.text }}</p>

    {% thumbnail post.image "960x339" crop="center"  upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}" weidth=50% height=25%>
    {% endthumbnail %}

    {{ post.group }} 
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}
</article>
</div>
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatewords:30 }} {% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
         
            <li class="list-group-item">
              <a href="{% url 'posts:post_edit' post.id %}">Редактирование записи</a>
            </li>
        
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }} 
            </li>
            <li class="list-group-item">    
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
            {% endif %}
            
            {% if not forloop.last %}<hr>{% endif %}   
            </li>
              <li class="list-group-item">
                Автор:
                  {% if post.author.get_full_name  %}
                  {{ post.author.get_full_name }}
                  {% else %}
                  {{ post.author.username }}
                  {% endif %}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
        </article>
        {% include 'posts/comments.html' %} 
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
     Профайл пользователя 
        {% if post.author.get_full_name  %}
        {{ post.author.get_full_name }}
         {% else %}
          {{author}}    
        {% endif %} 
{% endblock %}
{% block content %}
    </body>
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_count }}</h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      </div>
      <div class="container py-5">        
        <h1>Все посты пользователя {{author}} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>   
        <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {% if post.author.get_full_name  %}
              {{ post.author.get_full_name }}
               {% else %}
               {{ author }}    
              {% endif %} 
              <a href="">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <li>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          </li>
          <li>
            <a href="{% url 'posts:index' %}">Вернуться на главную</a>
            </li>
        </article>       
        {% if post.group %}  
        <li>Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </li> 

        {% endif %}        
        <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>
    </main>
    </body>
{% endblock %}